/* 🤖 this file was generated by svg-to-ts*/

import { CamfilIcon } from './build/camfil-icon.model';

export type IconNameSubset<
  T extends Readonly<CamfilIcon[]>
> = T[number]['name'];

export * from './build/camfilIcon-3dots.icon';
export * from './build/camfilIcon-add-camcard.icon';
export * from './build/camfilIcon-address-pin.icon';
export * from './build/camfilIcon-arrow-left.icon';
export * from './build/camfilIcon-arrow-right.icon';
export * from './build/camfilIcon-calendar.icon';
export * from './build/camfilIcon-camcard.icon';
export * from './build/camfilIcon-camfil-logo-cart.icon';
export * from './build/camfilIcon-cart.icon';
export * from './build/camfilIcon-checkmark.icon';
export * from './build/camfilIcon-chevron-left-fab.icon';
export * from './build/camfilIcon-chevron-right-fab.icon';
export * from './build/camfilIcon-comment.icon';
export * from './build/camfilIcon-compare.icon';
export * from './build/camfilIcon-contact.icon';
export * from './build/camfilIcon-copy.icon';
export * from './build/camfilIcon-create-camcard.icon';
export * from './build/camfilIcon-delete.icon';
export * from './build/camfilIcon-delivery-time.icon';
export * from './build/camfilIcon-delivery.icon';
export * from './build/camfilIcon-edit.icon';
export * from './build/camfilIcon-error.icon';
export * from './build/camfilIcon-excel.icon';
export * from './build/camfilIcon-eye.icon';
export * from './build/camfilIcon-globe.icon';
export * from './build/camfilIcon-inactive.icon';
export * from './build/camfilIcon-info.icon';
export * from './build/camfilIcon-lock.icon';
export * from './build/camfilIcon-logo.icon';
export * from './build/camfilIcon-maintenance.icon';
export * from './build/camfilIcon-menu.icon';
export * from './build/camfilIcon-minus-fab.icon';
export * from './build/camfilIcon-minus.icon';
export * from './build/camfilIcon-move.icon';
export * from './build/camfilIcon-package.icon';
export * from './build/camfilIcon-payment.icon';
export * from './build/camfilIcon-pdf.icon';
export * from './build/camfilIcon-play_arrow.icon';
export * from './build/camfilIcon-play-fab.icon';
export * from './build/camfilIcon-plus-fab.icon';
export * from './build/camfilIcon-plus.icon';
export * from './build/camfilIcon-print.icon';
export * from './build/camfilIcon-profile-fab.icon';
export * from './build/camfilIcon-question-mark.icon';
export * from './build/camfilIcon-quote.icon';
export * from './build/camfilIcon-sale.icon';
export * from './build/camfilIcon-search.icon';
export * from './build/camfilIcon-send.icon';
export * from './build/camfilIcon-settings.icon';
export * from './build/camfilIcon-spinner.icon';
export * from './build/camfilIcon-stock.icon';
export * from './build/camfilIcon-user.icon';
export * from './build/camfilIcon-users.icon';
export * from './build/camfilIcon-warehouse.icon';
export * from './build/camfilIcon-wishlist.icon';
export * from './build/completeIconSet';
export * from './build/camfil-icon.model';
