#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the active pull-requests

image: node:14

pipelines:
  pull-requests:
    '**':
      - step:
          name: List Files
          script:
            - node -v
            - npm -v
            - echo "$(ls -la)"
      - step:
          name: Install & Build Dependencies
          caches:
            - node
          artifacts:
            - node_modules/**
            - projects/organization-management/src/app/exports/**
            - projects/requisition-management/src/app/exports/**
            - projects/camfil-icons/src/exports/build/**
            - node_modules/intershop-tslint-rules/**
            - schematics/src/**/*.js
            - schematics/src/**/*.d.ts
            - src/app/extensions/**/exports/**
          script:
            - npm ci
            - npm run build:icons
            - npm run build:tslint-rules
            - npm run build:schematics
            - npm run synchronize-lazy-components -- --ci
          after-script:
            - cat $HOME/.npm/_logs/*
            - cat $(find /tmp/ng-** -name "angular-errors.log")
      - parallel:
          - step:
              name: Simulating Build
              caches:
                - node
              script:
                - npm run tsc:build-all -- --noEmit
              after-script:
                - cat $HOME/.npm/_logs/*
                - cat $(find /tmp/ng-** -name "angular-errors.log")
          - step:
              name: Code Linting
              caches:
                - node
              script:
                - npm run lint
              after-script:
                - cat $HOME/.npm/_logs/*
                - cat $(find /tmp/ng-** -name "angular-errors.log")
          - step:
              name: Unit Testing
              caches:
                - node
              script:
                - npm run test -- --forceExit --ci -w=4 -u
              after-script:
                - cat $HOME/.npm/_logs/*
                - cat $(find /tmp/ng-** -name "angular-errors.log")
