#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the active pull-requests

image: node:12

pipelines:
  pull-requests:
    '**':
      - step:
          name: List Files
          script:
            - echo "$(ls -la)"
      - step:
          name: Install Dependencies
          caches:
            - node
          artifacts:
            - node_modules/**
            - projects/camfil-icons/src/exports/build/**
          script:
            - npm install
            - npm install -g @angular/cli
            - npm run synchronize-lazy-components
            - npm run build:icons
          after-script:
            - cat /root/.npm/_logs/*
            - cat $(find /tmp/ng-** -name "angular-errors.log")
      - step:
          name: Code Linting
          caches:
            - node
          script:
            - npm run lint
          after-script:
            - cat /root/.npm/_logs/*
            - cat $(find /tmp/ng-** -name "angular-errors.log")
      - step:
          name: Unit Testing
          caches:
            - node
          script:
            - npm run test -- --changedSince=$BITBUCKET_PR_DESTINATION_BRANCH
          after-script:
            - cat /root/.npm/_logs/*
            - cat $(find /tmp/ng-** -name "angular-errors.log")
