FROM node:14 as buildstep
ENV CI=true
COPY . /workspace/
WORKDIR /workspace
RUN npm ci
RUN ./node_modules/.bin/ngcc
RUN npm run build:icons
RUN npm run build:schematics
RUN npm run synchronize-lazy-components
EXPOSE 8080
CMD npx ng serve --host 0.0.0.0 --disableHostCheck true --aot --port 8080
