# export appropriate ICM_BASE_URL and use with
# docker-compose -f templates/docker-compose.yml up --build

version: '3'
services:
  pwa:
    build:
      context: ..
      args:
        # configuration: local
        configuration: production
        serviceWorker: 'false'
    environment:
      - NODE_OPTIONS="--max-old-space-size=16384"
      - LOGGING=on
      - ICM_BASE_URL=${ICM_BASE_URL}
      - ICC_TOKEN=${ICC_TOKEN}
      - ICC_PROXY_URL=${ICC_PROXY_URL}
      - TRUST_ICM=true
      - PROXY_ICM=${PROXY_ICM}
      - SSR_HYBRID=true
      - GTM_TOKEN=${GTM_TOKEN}
      - DISPLAY_VERSION="development"
      # - PROMETHEUS=on
  nginx:
    build: ../nginx
    depends_on:
      - pwa
    environment:
      ICM_BASE_URL: ${ICM_BASE_URL}
      UPSTREAM_PWA: 'http://pwa:4200'
      DEBUG: 1
      CACHE: 0
      PAGESPEED: 0
      # PROMETHEUS: 1
      # COMPRESSION: 0
      # DEVICE_DETECTION: 0
    ports:
      - '4200:80'
      # - '9113:9113'
